In [1]:
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.decomposition import PCA 
from sklearn import datasets

In [2]:
ds=datasets.load_iris()

In [4]:
X=ds['data']
y=ds['target']

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test ,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=3)


In [8]:
X_train

array([[4.8, 3. , 1.4, 0.3],
       [5. , 3.2, 1.2, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.1, 2.8, 4.7, 1.2],
       [4.9, 3.1, 1.5, 0.2],
       [6.3, 3.4, 5.6, 2.4],
       [5.1, 3.8, 1.5, 0.3],
       [6.5, 3. , 5.5, 1.8],
       [5.7, 2.9, 4.2, 1.3],
       [5. , 3.6, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [6.8, 3.2, 5.9, 2.3],
       [5.9, 3.2, 4.8, 1.8],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.1, 2.5, 3. , 1.1],
       [6.4, 3.1, 5.5, 1.8],
       [6.3, 3.3, 6. , 2.5],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 3.3, 5.7, 2.1],
       [5.7, 3. , 4.2, 1.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [7.7, 3.8, 6.7, 2.2],
       [5.8, 2.8, 5.1, 2.4],
       [5.7, 2.8, 4.1, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [6.3, 2.3, 4.4, 1.3],
       [5.1, 3.8, 1.9, 0.4],
       [5.5, 3.5, 1.3, 0.2],
       [6.4, 3.2, 5.3, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.9, 3

In [9]:
pca=PCA(n_components=3) # converts 4d to 3d

In [11]:
pca

PCA(n_components=3)

In [12]:
X_train=pca.fit_transform(X_train)

In [13]:
X_train

array([[-2.76768609e+00, -2.82426425e-01, -7.85895270e-02],
       [-2.92115916e+00,  3.63666101e-02, -1.36272591e-01],
       [ 1.36734992e+00, -5.93460880e-01,  2.59916013e-01],
       [ 1.22610030e+00,  6.74580848e-01, -4.13751488e-01],
       [ 8.68758735e-01, -1.80379684e-01, -2.69004371e-01],
       [-2.69041419e+00, -1.46411477e-01, -1.28856805e-01],
       [ 2.09824773e+00,  1.11513712e-01,  7.08696295e-01],
       [-2.63938519e+00,  4.86010575e-01,  2.34636594e-01],
       [ 1.89812024e+00,  3.55735579e-02,  7.46852668e-03],
       [ 3.25942776e-01, -3.05521418e-01,  5.11925136e-02],
       [-2.78081263e+00,  3.00910907e-01,  1.09204132e-01],
       [-2.83976183e+00, -2.58003228e-01, -1.94828591e-01],
       [ 2.51217282e+00,  2.57674016e-01,  2.65979284e-01],
       [ 1.06888623e+00, -1.04439530e-01,  4.32223398e-01],
       [-2.56185397e+00,  6.19831612e-01, -4.92199088e-02],
       [-2.66337742e+00, -5.67053004e-03,  1.08767664e-01],
       [-9.57914159e-01, -7.88440386e-01

In [15]:
pca.transform(X_test)

array([[-2.88999697, -0.25327723,  0.09306316],
       [-2.79606307, -0.34152883,  0.03741949],
       [-2.46601759,  0.37488467, -0.11136287],
       [-2.56126399, -0.16962396, -0.2399259 ],
       [-2.4395708 ,  1.30508118,  0.31696759],
       [ 3.73677762,  0.25454174, -0.55144356],
       [ 0.11516365, -0.70014395, -0.08343335],
       [-2.86979952, -0.118473  ,  0.27010404],
       [ 1.92162155, -0.18275628,  0.06267572],
       [ 0.87033056,  0.45018663, -0.3183869 ],
       [ 0.19679258, -0.28230894,  0.16226161],
       [-3.03060283, -0.51562762,  0.08117566],
       [ 0.17685445, -0.41930708, -0.2483685 ],
       [ 0.13100407, -0.84715978, -0.2023547 ],
       [ 2.26287354,  0.15114644,  0.30861254],
       [-2.82286823,  0.22993508,  0.10404598],
       [ 1.24309295, -0.33694736, -0.37624464],
       [ 3.01698728,  0.66652288, -0.34413693],
       [ 1.29799823, -0.80298374,  0.25072262],
       [-3.04644325, -0.36861178,  0.20009701],
       [ 1.20621596, -0.20335384,  0.028

In [18]:
pca.components_   #  Eigen vectors

array([[ 0.35216296, -0.0792021 ,  0.86013688,  0.36037873],
       [ 0.65039118,  0.73507916, -0.14743684, -0.12211598],
       [-0.55425432,  0.59460676,  0.0381701 ,  0.58119532]])

In [20]:
pca.explained_variance_ratio_  # details of captured variance

array([0.92422685, 0.05195908, 0.0193837 ])