# Logistic Regression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
from sklearn.datasets import load_iris

In [6]:
dataset=load_iris()

In [7]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [11]:
 print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [12]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [17]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)


In [18]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [20]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [21]:
df['target']=dataset.target

In [22]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [24]:
 df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [50]:
df_copy=df[df['target']!=2]

In [51]:
df_copy.shape

(100, 5)

In [5]:
from sklearn.model_selection import train_test_split

In [53]:
X=df_copy.iloc[:,:-1]


In [56]:
X.shape

(100, 4)

In [60]:
y=df_copy.iloc[:,-1]


In [61]:
y.shape

(100,)

In [63]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [64]:
X_train.shape

(75, 4)

In [65]:
from sklearn.linear_model import LogisticRegression

In [66]:
regressor=LogisticRegression()

In [67]:
regressor

LogisticRegression()

In [68]:
regressor.fit(X_train,y_train)

LogisticRegression()

In [69]:
y_pred=regressor.predict(X_test)

In [70]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1])

# Confusion Matrix Acuuracy Precision Recall

In [71]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [72]:
confusion_matrix(y_test,y_pred)

array([[14,  0],
       [ 0, 11]], dtype=int64)

In [73]:
accuracy_score(y_test,y_pred)

1.0

In [74]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        14\n           1       1.00      1.00      1.00        11\n\n    accuracy                           1.00        25\n   macro avg       1.00      1.00      1.00        25\nweighted avg       1.00      1.00      1.00        25\n'

In [75]:
from sklearn.model_selection import KFold

In [76]:
cv=KFold(n_splits=5,shuffle=True)

In [77]:
cv

KFold(n_splits=5, random_state=None, shuffle=True)

In [78]:
from sklearn.model_selection import cross_val_score

In [82]:
# Do cross validation
score=cross_val_score(regressor,X_train,y_train,scoring='accuracy',cv=cv)

In [83]:
score

array([1., 1., 1., 1., 1.])

In [84]:
final_accuracy=np.mean(score)

In [85]:
final_accuracy

1.0

# Logistic Regression Hyper Parameter  Tuning

In [41]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
 

In [3]:
X,y=make_classification(n_samples=1000,n_features=10,n_informative=5,n_redundant=5,n_classes=2,random_state=42)

In [6]:
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

# HyperParameter Tuning
# GridSearchCV

In [25]:
from sklearn.model_selection import GridSearchCV

In [26]:
parameters={'penalty':('l1','l2','elasicnet'),'C':[1,10,20,30]}

In [27]:
classifier=LogisticRegression()

In [29]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [30]:
clf.fit(X_train,y_train)

C:\Users\shree\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
40 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\shree\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\shree\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shree\anaconda3\Lib\site-packages\sklearn\linear_model\_lo

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasicnet')})

In [31]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [32]:
clf.best_score_

0.8275

In [33]:
classifier=LogisticRegression(C=1,penalty='l2')

In [34]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [35]:
y_pred=classifier.predict(X_test)

In [36]:
classifier.predict_proba(X_test)

array([[8.27439567e-01, 1.72560433e-01],
       [8.53544633e-01, 1.46455367e-01],
       [1.13368459e-01, 8.86631541e-01],
       [2.83765274e-01, 7.16234726e-01],
       [1.42745659e-01, 8.57254341e-01],
       [7.47454472e-01, 2.52545528e-01],
       [9.37948203e-01, 6.20517974e-02],
       [9.62811851e-01, 3.71881494e-02],
       [8.85548407e-01, 1.14451593e-01],
       [9.98686022e-01, 1.31397824e-03],
       [1.43555461e-01, 8.56444539e-01],
       [4.84664599e-01, 5.15335401e-01],
       [3.05707745e-01, 6.94292255e-01],
       [4.40758573e-01, 5.59241427e-01],
       [3.26259494e-01, 6.73740506e-01],
       [8.90954703e-01, 1.09045297e-01],
       [9.25581207e-01, 7.44187933e-02],
       [6.07547733e-01, 3.92452267e-01],
       [9.34638103e-01, 6.53618967e-02],
       [1.75304926e-01, 8.24695074e-01],
       [9.33781798e-01, 6.62182018e-02],
       [1.44598853e-01, 8.55401147e-01],
       [2.24035714e-01, 7.75964286e-01],
       [2.69191345e-01, 7.30808655e-01],
       [3.285424

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [38]:
confusion_matrix(y_test,y_pred)

array([[81, 19],
       [23, 77]], dtype=int64)

In [39]:
accuracy_score(y_test,y_pred)

0.79

In [40]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.78      0.81      0.79       100\n           1       0.80      0.77      0.79       100\n\n    accuracy                           0.79       200\n   macro avg       0.79      0.79      0.79       200\nweighted avg       0.79      0.79      0.79       200\n'

# Multiclaass Classification

In [42]:
X,y=make_classification(n_samples=1000,n_features=10,n_informative=5,n_redundant=5,n_classes=3,random_state=42)

In [43]:
y

array([0, 0, 1, 0, 0, 1, 2, 2, 0, 2, 1, 2, 1, 2, 1, 1, 0, 2, 2, 2, 1, 0,
       0, 0, 2, 2, 1, 1, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 1, 1, 1, 2,
       2, 2, 1, 2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 1, 1,
       2, 0, 0, 1, 0, 0, 1, 2, 1, 2, 1, 0, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 0, 2, 0, 1, 0, 2, 0,
       2, 0, 1, 2, 2, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1,
       0, 1, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 2,
       0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 2, 2, 1, 1, 2, 2, 0, 1, 1,
       0, 0, 2, 1, 0, 0, 1, 0, 0, 2, 2, 1, 2, 2, 0, 0, 1, 1, 0, 2, 0, 0,
       0, 2, 2, 2, 0, 2, 1, 1, 0, 2, 2, 1, 1, 2, 2, 0, 2, 1, 0, 2, 1, 2,
       1, 2, 0, 2, 0, 0, 0, 2, 0, 1, 1, 2, 1, 0, 1, 0, 2, 1, 0, 2, 0, 2,
       0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 2, 0, 0, 1,

In [44]:
model=LogisticRegression(multi_class='ovr',solver='lbfgs')

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [48]:
model.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [49]:
y_pred=model.predict(X_test)

In [50]:
model.predict_proba(X_test)

array([[1.03558920e-01, 6.81583162e-01, 2.14857918e-01],
       [4.93247668e-01, 3.27440274e-01, 1.79312058e-01],
       [2.77898508e-01, 4.03127164e-01, 3.18974327e-01],
       [4.79936783e-03, 6.59475265e-01, 3.35725367e-01],
       [6.17966904e-01, 5.30442251e-02, 3.28988871e-01],
       [7.19095033e-01, 2.55304529e-04, 2.80649662e-01],
       [6.50831719e-02, 5.34588480e-01, 4.00328348e-01],
       [4.22391618e-01, 1.00489926e-01, 4.77118455e-01],
       [1.69228490e-01, 3.79802909e-01, 4.50968601e-01],
       [3.63489761e-01, 1.76792578e-01, 4.59717661e-01],
       [4.79832325e-01, 1.47558313e-01, 3.72609362e-01],
       [8.19507625e-01, 8.75258003e-03, 1.71739795e-01],
       [5.70090062e-01, 8.86859415e-03, 4.21041344e-01],
       [7.97025314e-01, 1.06381422e-02, 1.92336544e-01],
       [6.90399578e-01, 5.23121202e-02, 2.57288302e-01],
       [6.94370549e-01, 1.17216389e-02, 2.93907812e-01],
       [4.00574049e-01, 1.00720708e-01, 4.98705243e-01],
       [5.78841683e-02, 4.93663

In [51]:
confusion_matrix(y_pred,y_test)

array([[54,  6, 14],
       [ 7, 45, 17],
       [ 7, 14, 36]], dtype=int64)

In [52]:
accuracy_score(y_pred,y_test)

0.675

In [53]:
classification_report(y_pred,y_test)

'              precision    recall  f1-score   support\n\n           0       0.79      0.73      0.76        74\n           1       0.69      0.65      0.67        69\n           2       0.54      0.63      0.58        57\n\n    accuracy                           0.68       200\n   macro avg       0.67      0.67      0.67       200\nweighted avg       0.69      0.68      0.68       200\n'