In [3]:
import numpy as np


In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
# range function cant give float value

In [6]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
# to get fraction value we can use np.arange function 

In [8]:
np.arange(.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [9]:
# step size can also be a fraction

In [12]:
list(np.arange(.4,10.4,0.22))

[0.4,
 0.62,
 0.84,
 1.06,
 1.2799999999999998,
 1.5,
 1.7199999999999998,
 1.94,
 2.1599999999999997,
 2.38,
 2.5999999999999996,
 2.82,
 3.0399999999999996,
 3.2599999999999993,
 3.4799999999999995,
 3.6999999999999997,
 3.9199999999999995,
 4.14,
 4.359999999999999,
 4.58,
 4.8,
 5.02,
 5.24,
 5.46,
 5.68,
 5.8999999999999995,
 6.119999999999999,
 6.34,
 6.56,
 6.779999999999999,
 7.0,
 7.22,
 7.4399999999999995,
 7.659999999999999,
 7.879999999999999,
 8.1,
 8.319999999999999,
 8.54,
 8.76,
 8.979999999999999,
 9.2,
 9.42,
 9.639999999999999,
 9.86,
 10.08,
 10.299999999999999]

In [15]:
np.linspace(1,5,20) # divides 1 to 5 into 20 spaces and generates value

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [16]:
np.linspace(1,20,20)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [17]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

#The `np.logspace` function is a NumPy function used to generate an array of numbers spaced evenly on a logarithmic scale. The function takes three arguments: `start`, `stop`, and `num`. It returns an array of `num` numbers spaced evenly on a logarithmic scale between 10 raised to the power of `start` and 10 raised to the power of `stop`.

In your example, `np.logspace(1, 5, 10)` generates an array of 10 numbers spaced evenly on a logarithmic scale between 10^1 (10) and 10^5 (100000). Here's the result:

Each number in the array is the result of raising 10 to a power that ranges from 1 to 5, with a total of 10 evenly spaced steps. This is useful when you want to generate numbers for plotting or calculations that span several orders of magnitude on a logarithmic scale.

In [18]:
# by default base is 10
# if we need other base we can define as follows
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [19]:
np.zeros(5)  # generates 5 zeros

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,4)) # generates 3X4 zero matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.zeros((3,4,2))  # generates 3 4X2 matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [24]:
 np.ones(5)  # generates 5 ones

array([1., 1., 1., 1., 1.])

In [26]:
ar=np.ones((3,4))

In [27]:
ar

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
ar+5  # adds 5 to all array elements

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [31]:
arr2=np.eye(5)  # gives identity matrix of order 5

In [32]:
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
#convert array to data frame

In [34]:
import pandas as pd

In [35]:
pd.DataFrame(arr2)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [1]:
# generate random data

In [5]:
np.random.rand(2,3)  # generates 2X3 data set

array([[0.25550002, 0.51284555, 0.89624892],
       [0.96461669, 0.53222247, 0.48738027]])

In [6]:
np.random.randn(2,3)  # generates standard normal distribution data  means  whose mean is 0 and standard deviation is 1

array([[ 0.24375884,  0.42260264, -0.64954972],
       [ 0.54478919,  1.10747246,  2.61318963]])

In [8]:
arr3=np.random.randint(1,5,(3,4)) #generates integer between 1 to 5  in a 3X4 matrix

In [10]:
arr3.shape

(3, 4)

In [11]:
# change the shape
arr3.reshape(6,2)

array([[3, 2],
       [2, 2],
       [3, 1],
       [1, 1],
       [3, 1],
       [1, 2]])

In [12]:
arr4=np.random.randint(1,10,(5,6))

In [13]:
arr4

array([[9, 2, 7, 9, 1, 8],
       [4, 1, 5, 7, 9, 4],
       [6, 9, 9, 7, 1, 7],
       [5, 9, 1, 7, 1, 2],
       [2, 9, 2, 8, 7, 9]])

In [14]:
arr4>8


array([[ True, False, False,  True, False, False],
       [False, False, False, False,  True, False],
       [False,  True,  True, False, False, False],
       [False,  True, False, False, False, False],
       [False,  True, False, False, False,  True]])

In [15]:
# to get all values greater than 8

arr4[arr4>8]

array([9, 9, 9, 9, 9, 9, 9, 9])

In [16]:
arr4

array([[9, 2, 7, 9, 1, 8],
       [4, 1, 5, 7, 9, 4],
       [6, 9, 9, 7, 1, 7],
       [5, 9, 1, 7, 1, 2],
       [2, 9, 2, 8, 7, 9]])

In [17]:
# acces elements

In [18]:
arr4[0]

array([9, 2, 7, 9, 1, 8])

In [19]:
arr4[0][0]

9

In [21]:
arr4[[0],[0,1]]

array([9, 2])

In [29]:
arr4[2:4,[2,3]]

array([[9, 7],
       [1, 7]])

In [34]:
arr5=np.random.randint(1,5,(3,3))
arr6=np.random.randint(2,6,(3,3))

In [35]:
arr5

array([[4, 4, 1],
       [1, 3, 1],
       [3, 1, 4]])

In [36]:
arr6

array([[5, 4, 3],
       [2, 5, 5],
       [2, 3, 2]])

In [38]:
arr5+arr6  # adds array1 and array2

array([[9, 8, 4],
       [3, 8, 6],
       [5, 4, 6]])

In [39]:
arr5* arr6  #performs index wise multiplication not a matrix multiplication

array([[20, 16,  3],
       [ 2, 15,  5],
       [ 6,  3,  8]])

In [40]:
# to do matrix multiplication we have to use @
arr5@arr6

array([[30, 39, 34],
       [13, 22, 20],
       [25, 29, 22]])

In [41]:
arr5-arr6

array([[-1,  0, -2],
       [-1, -2, -4],
       [ 1, -2,  2]])

In [42]:
arr5/arr6

array([[0.8       , 1.        , 0.33333333],
       [0.5       , 0.6       , 0.2       ],
       [1.5       , 0.33333333, 2.        ]])

## NUMPY BROADCASTING

In [44]:
arr=np.zeros((3,4))

In [45]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [47]:
a=np.array([1,2,3,4])

In [49]:
arr+a  # adds a to arr row wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [56]:
b=np.array([[1,2,3]])

In [52]:
# cant add b to directly to arr as , number of rows didnt match

In [58]:
#to add b to arr we have to add column wise so fisgt we have to take b transpose and add|

In [59]:
b.T

array([[1],
       [2],
       [3]])

In [63]:
a1=arr+b.T
a1

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [60]:
# perform squrt

In [64]:
np.sqrt(a1)

array([[1.        , 1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081]])

In [65]:
np.log10(a1)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.30103   , 0.30103   , 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125]])

In [66]:
np.exp(a1)

array([[ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [20.08553692, 20.08553692, 20.08553692, 20.08553692]])

In [67]:
np.min(a1)

1.0

In [68]:
np.max(a1)

3.0