# ARRAY MANIPULATION

In [1]:
import numpy as np

In [3]:
arr= np.random.randint(1,10,(4,4))

In [4]:
arr

array([[4, 2, 2, 2],
       [3, 7, 8, 8],
       [7, 9, 3, 6],
       [8, 5, 2, 3]])

In [5]:
arr.reshape(8,2)

array([[4, 2],
       [2, 2],
       [3, 7],
       [8, 8],
       [7, 9],
       [3, 6],
       [8, 5],
       [2, 3]])

In [6]:
#Transpose

In [7]:
arr.T

array([[4, 3, 7, 8],
       [2, 7, 9, 5],
       [2, 8, 3, 2],
       [2, 8, 6, 3]])

In [12]:
arr.flatten() # returns 1d array

array([4, 2, 2, 2, 3, 7, 8, 8, 7, 9, 3, 6, 8, 5, 2, 3])

<function ndarray.flatten>

In [14]:
np.expand_dims(arr,axis=1)  # increase the dimension by one

array([[[4, 2, 2, 2]],

       [[3, 7, 8, 8]],

       [[7, 9, 3, 6]],

       [[8, 5, 2, 3]]])

In [15]:
data=np.array([[1],[2],[3]])

In [18]:
np.squeeze(data)  # squeezes into 1 d array

array([1, 2, 3])

In [19]:
np.repeat(data,2) # repead the elements in data 2 times

array([1, 1, 2, 2, 3, 3])

In [25]:
np.roll(data,1) # roll the elements from last position and re insert it into firs  ROTATES THE DATASETt

array([[3],
       [1],
       [2]])

In [29]:
np.diag(np.array(range(1,5)))  # returns 2 d matrix by placing specified elements at the diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Binary Operation

In [31]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [32]:
arr1

array([[8, 8, 6, 2],
       [5, 2, 6, 5],
       [2, 9, 6, 1]])

In [33]:
arr2

array([[6, 7, 2, 9],
       [5, 4, 5, 8],
       [8, 6, 2, 1]])

In [34]:
arr1+arr2

array([[14, 15,  8, 11],
       [10,  6, 11, 13],
       [10, 15,  8,  2]])

In [35]:
arr1*arr2

array([[48, 56, 12, 18],
       [25,  8, 30, 40],
       [16, 54, 12,  1]])

In [36]:
arr1/arr2

array([[1.33333333, 1.14285714, 3.        , 0.22222222],
       [1.        , 0.5       , 1.2       , 0.625     ],
       [0.25      , 1.5       , 3.        , 1.        ]])

In [37]:
 arr1**arr2

array([[ 262144, 2097152,      36,     512],
       [   3125,      16,    7776,  390625],
       [    256,  531441,      36,       1]])

In [38]:
-arr1

array([[-8, -8, -6, -2],
       [-5, -2, -6, -5],
       [-2, -9, -6, -1]])

In [39]:
arr1>arr2

array([[ True,  True,  True, False],
       [False, False,  True, False],
       [False,  True,  True, False]])

In [40]:
# Numpy String Function

In [43]:
arr=np.array(["Sudh","kumar"])
arr

array(['Sudh', 'kumar'], dtype='<U5')

In [44]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [45]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [46]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [47]:
# NUMPY MATH FUNCTIONS

In [48]:
arr1

array([[8, 8, 6, 2],
       [5, 2, 6, 5],
       [2, 9, 6, 1]])

In [49]:
np.sin(arr1)

array([[ 0.98935825,  0.98935825, -0.2794155 ,  0.90929743],
       [-0.95892427,  0.90929743, -0.2794155 , -0.95892427],
       [ 0.90929743,  0.41211849, -0.2794155 ,  0.84147098]])

In [50]:
np.cos(arr1)

array([[-0.14550003, -0.14550003,  0.96017029, -0.41614684],
       [ 0.28366219, -0.41614684,  0.96017029,  0.28366219],
       [-0.41614684, -0.91113026,  0.96017029,  0.54030231]])

In [51]:
np.tan(arr1)

array([[-6.79971146, -6.79971146, -0.29100619, -2.18503986],
       [-3.38051501, -2.18503986, -0.29100619, -3.38051501],
       [-2.18503986, -0.45231566, -0.29100619,  1.55740772]])

In [52]:
np.log10(arr1)

array([[0.90308999, 0.90308999, 0.77815125, 0.30103   ],
       [0.69897   , 0.30103   , 0.77815125, 0.69897   ],
       [0.30103   , 0.95424251, 0.77815125, 0.        ]])

In [53]:
np.exp(arr1)

array([[2.98095799e+03, 2.98095799e+03, 4.03428793e+02, 7.38905610e+00],
       [1.48413159e+02, 7.38905610e+00, 4.03428793e+02, 1.48413159e+02],
       [7.38905610e+00, 8.10308393e+03, 4.03428793e+02, 2.71828183e+00]])

In [54]:
np.power(arr1,2)

array([[64, 64, 36,  4],
       [25,  4, 36, 25],
       [ 4, 81, 36,  1]], dtype=int32)

In [55]:
np.mean(arr1)

5.0

In [57]:
np.median(arr1)

5.5

In [59]:
np.std(arr1)

2.581988897471611

In [61]:
np.var(arr1)   # variance

6.666666666666667

In [62]:
np.min(arr1)

1

In [63]:
np.max(arr1)

9

In [64]:
# arithmatic

In [65]:
arr1

array([[8, 8, 6, 2],
       [5, 2, 6, 5],
       [2, 9, 6, 1]])

In [66]:
arr2

array([[6, 7, 2, 9],
       [5, 4, 5, 8],
       [8, 6, 2, 1]])

In [67]:
arr1-arr2

array([[ 2,  1,  4, -7],
       [ 0, -2,  1, -3],
       [-6,  3,  4,  0]])

In [68]:
np.subtract(arr1,arr2)

array([[ 2,  1,  4, -7],
       [ 0, -2,  1, -3],
       [-6,  3,  4,  0]])

In [69]:
np.multiply(arr1,arr2)

array([[48, 56, 12, 18],
       [25,  8, 30, 40],
       [16, 54, 12,  1]])

In [70]:
np.mod(arr1,arr2)  # remainder

array([[2, 1, 0, 2],
       [0, 2, 1, 5],
       [2, 3, 0, 0]])

In [71]:
np.power(arr1,arr2)

array([[ 262144, 2097152,      36,     512],
       [   3125,      16,    7776,  390625],
       [    256,  531441,      36,       1]])

In [72]:
np.sqrt(arr1)

array([[2.82842712, 2.82842712, 2.44948974, 1.41421356],
       [2.23606798, 1.41421356, 2.44948974, 2.23606798],
       [1.41421356, 3.        , 2.44948974, 1.        ]])

In [73]:
# Statistics

In [74]:
np.mean(arr1)

5.0

In [75]:
np.std(arr1)

2.581988897471611

In [76]:
np.median(arr1)

5.5