In [1]:
# sort Search and counting functions

In [2]:
import numpy as np

In [5]:
arr=np.array([2,4,98,6])

In [6]:
np.sort(arr)

array([ 2,  4,  6, 98])

In [7]:
# search sorted finds the position where a given element to be inserted to maintain the order.

In [8]:
np.searchsorted(arr,5)

2

In [11]:
arr1=np.random.randint(0,10,(2,3))

In [12]:
arr1

array([[1, 8, 6],
       [6, 1, 7]])

In [13]:
np.count_nonzero(arr1)

6

In [15]:
np.where(arr>0)  #returns the indexes where entries greater than 0

(array([0, 1, 2, 3], dtype=int64),)

In [17]:
np.extract(arr>2,arr)  # extracts data based on condition

array([ 4, 98,  6])

In [18]:
# linear algebra

In [25]:
arr1=np.random.randint([[2,3],[4,5]])
arr1

array([[0, 2],
       [2, 4]])

In [27]:
arr2=np.random.randint([[5,3],[2,5]])
arr2

array([[3, 0],
       [1, 2]])

In [30]:
np.dot(arr1,arr2)  # same as matrix multiplication

array([[ 2,  4],
       [10,  8]])

In [29]:
arr1@arr2

array([[ 2,  4],
       [10,  8]])