In [5]:
import numpy as np

In [15]:
l=[1,2,3,4,5]

In [16]:
arr=np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim # gives dimension of array

1

In [6]:
# matrix always has 2 dimensions

In [8]:
mat=np.matrix(l)

In [9]:
np.asanyarray(l)  # converts any type to array

array([1, 2, 3, 4, 5])

fromfunction() takes function as argument based on arg generates dataset 

In [10]:
np.fromfunction(lambda i,j :i==j ,(3,3))  # 3,3 is size of dataset

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [1]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [2]:
# we can do this using numpy as follows

In [3]:
iterable=(i*i for i in range(5))

In [6]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [7]:
# from string we can generate the array

In [9]:
np.fromstring('23 45 56',sep=' ')

array([23., 45., 56.])

In [10]:
 # generate array from comma separated string by giving sep as ,

In [12]:
np.fromstring('23,45,56',sep=',')

array([23., 45., 56.])

In [18]:
arr.size  # gives size of array

5

In [20]:
arr.shape  # gives dimension of array

(5,)

In [22]:
arr.dtype  # gives datatype of array

dtype('int32')